# Generated by Django 5.0.3 on 2024-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0002_profile_first_name_profile_last_name_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
