# Generated by Django 5.0.3 on 2024-03-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='country',
        ),
    ]
